from __future__ import annotations

from typing import Protocol

from .core import Message


class ThreadClient(Protocol):
    def list_messages(self, thread_id: str) -> list[Message]: ...
    def post(self, content: str, thread_id: str | None = None) -> Message: ...
    def edit(self, message_id: str, content: str) -> Message: ...
    def delete(self, message_id: str) -> None: ...
