name: Build dist branch

on:
  push:
    branches: [ts]
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: runsascoded/npm-dist@v1
        with:
          source_ref: ts
          dist_branch: ts-dist
